application: ericodummytestapp2
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /js
  static_dir: static/js
- url: /bootstrap
  static_dir: static/bootstrap
- url: /
  static_files: templates/index.html
  upload: templates/index.html
# Endpoints handler
- url: /_ah/spi/.*
  script: chamada_api.application

libraries:
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0

